# Generated by Django 4.2.11 on 2024-06-09 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
