# Generated by Django 4.2.11 on 2024-06-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_project_freelancer_alter_project_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
